services:
  - type: web
    name: wokers-ng-auto-bot
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: python bot.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.13

      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: TELEGRAM_CHANNEL
        value: "@wokersng"

      - key: POST_INTERVAL_MINUTES
        value: "120"

      - key: POST_ON_START
        value: "true"